namespace Test
{
  /* test string stuff */
  constant ANSWER_A = "the answer to all questions";
  constant ANSWER_B = 42;
  constant ULTIMATE_ANSWER = (ANSWER_A " is " ANSWER_B);

  choice YesNoUndecided {
    Undecided @= (0, "Undecided"), /* need neutral(...) */
    Yes @= (1, "Yes"),
    No @= (2, "No")
  };

  record Position {
    Real x @= ("X", "", 0.0, -10.0, 10.0, 1, ":readwrite");
    Real y @= ("Y", "", 0.0, -10.0, 10.0, 1, ":readwrite");
    YesNoUndecided relevant; /* default */
  };

  record SickGenericThings {
    /*
     * FIXME: Tim? You opinion?
     * currently sfi_param_spec_Rec is already used for another thing
     * (for sfidl telling that some parameter has a record type)
     */
    Rec   rec   @= Record("Rec", "", ":readwrite");
    PSpec pspec @= ("Param Spec", "", ":readwrite");
  };

  sequence PositionSeq {
    Position positions @= ("Position", "", ":readwrite");
  };
};
/* vim:set ts=8 sts=2 sw=2: */
